name: Build InterCalc

on:
  push:
    branches:
      - qtversion

jobs:
  nuitka-qt-build:
    if: startsWith(github.ref, 'refs/heads/qtversion') || startsWith(github.ref, 'refs/heads/main')
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyside6

      - name: Build Qt GUI with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/main.py
          mode: onefile
          enable-plugins: pyside6
          output-dir: dist
          include-data-dir: src/icons=icons

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Qt-Windows-nuitka
          path: dist/
