name: Build InterCalc (Windows)

on:
  push:
    branches:
      - qtversion

jobs:
  nuitka-qt-build:
    if: startsWith(github.ref, 'refs/heads/qtversion')
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka PySide6

      - name: Build with Nuitka
        run: |
          nuitka --onefile --enable-plugin=pyside6 --output-dir=dist src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Qt-Windows-nuitka
          path: dist/
